// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcx145O7dex8-5NsU23QVTC6LTC6w8nww',
    appId: '1:346703991164:web:ff34864e1d6e26602614f9',
    messagingSenderId: '346703991164',
    projectId: 'zirofit-6e174',
    authDomain: 'zirofit-6e174.firebaseapp.com',
    storageBucket: 'zirofit-6e174.firebasestorage.app',
    measurementId: 'G-HCN3X64NFR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaLjWnRJEE93i5R6L570AsAYvFdg0aD1U',
    appId: '1:346703991164:android:fddaf8dbe0b89c5e2614f9',
    messagingSenderId: '346703991164',
    projectId: 'zirofit-6e174',
    storageBucket: 'zirofit-6e174.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2n8M3SLjKJYxeUzeR65Lg41w1VAlGh5Y',
    appId: '1:346703991164:ios:551525a07a083fb32614f9',
    messagingSenderId: '346703991164',
    projectId: 'zirofit-6e174',
    storageBucket: 'zirofit-6e174.firebasestorage.app',
    iosBundleId: 'health.ziro.app',
  );
}
